
.TH TURKMAN 1 2025-02-19 GNU 

.SH İSİM
turkman \- otomatik man sayfaları çeviricisi (Türkçe).

.SH KULLANIM
.B turkman
[\fIseçenek\fR]
\fIkomut\fR

.SH AÇIKLAMA
.B turkman
komut satırında çalışan ve man sayfalarını otomatik olarak Türkçeye çeviren bir uygulamadır.

.SH SEÇENEKLER

.TP
.BR \-h ", " \-? ", " \-\-help
bu yardım sayfasını görüntüler.

.TP
.BR \-y ", " \-\-yardım ", " \-\-yardim
bu yardım sayfasını Türkçe olarak görüntüler.

.TP
.BR \-l ", " \-\-less "
less menüsünü görüntüler. Kullanıcıların man sayfalarını nasıl okuyacaklarını anlamalarına yardımcı olur.

.TP
.BR \-trl ", " \-\-trless "
less menüsünü Türkçe olarak görüntüler. Kullanıcıların man sayfalarını nasıl okuyacaklarını anlamalarına yardımcı olur.

.TP
.BR \-v ", " \-\-version 
.B turkman
uygulamasının sürümünü görüntüler.

.SH BİLGİ 
Daha fazla bilgi için ziyaret edin: https://github.com/mmapro12/turkman

.SH YAZAR
Mohamad Bashir Alnirabani (GitHub: mmmapro12) <asia172007@gmail.com>

