.TH TURKMAN 1 2025-02-19 GNU

.SH ADI
turkman \- man sayfalarını otomatik olarak Türkçeye çeviren bir komut satırı uygulamasıdır.

.SH ÖZET
.B turkman
[\fIseçenek\fR]
\fIkomut\fR

.SH AÇIKLAMA
.B turkman
komut satırı uygulaması, man sayfalarını otomatik olarak Türkçeye çevirir.

.SH SEÇENEKLER

.TP
.BR \-h ", " \-? ", " \-\-help
bu yardım bilgilerini görüntüler.

.TP
.BR \-trl ", " \-\-trless ", " \-\-yardım ", " \-\-yardim
Türkçe'de less menüsünü görüntüler. Kullanıcıların man sayfalarını nasıl okumaları gerektiğini anlamalarına yardımcı olur.

.SH YAZAR
mmapro12 <asia172007@gmail.com>

